### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by lukasbystricky** [chapkachapka/maria-edgeworth_castle-rackrent#1]
- [x] Rename part-1.xhtml and part-2.xhtml to chapter-1 and chapter-2. Update spine, manifest etc.
- [x] Run semanticate again, this should make one change that should be accepted
- [x] In endnote-13, the word "beast" is inside double quotes, but should only be single-quoted
- [x] Also in endnote-13, there's a space missing in `<abbr>p.</abbr>84`
- [x] Spelling mistake in long description: "Thady realates ..."
- [x] In content.opf you should add the following loc id for David Widger: `<meta property="se:url.authority.nacoaf" refines="#transcriber-2">http://id.loc.gov/authorities/names/no2011017869</meta>`
- [x] Italics: I think this will be most time consuming issue. All foreign words or phrases (i.e. words that aren't in the _unabridged_ Merriam Webster dictionary) should be italicized. This includes quotes, for example in endnote-2 "Humi mantilia sternunt", as well as the Virgil and Ovid quotes in endnote-3. See [SEMOS 8.2.9.6](https://standardebooks.org/manual/1.7.3/single-page#8.2.9.6) for the CSS to apply italics to an entire blockquote. Words like "Whillaluh" and "⁠Ullaloo" should also be italicized and tagged ("Whillaluh" appears only in the unabridged MW). "Cantred" and "carterons" should be tagged. There are probably others.
- [x] In the Google Groups post Alex said that the glossary terms should be appended with `<cite>Editor</cite>`. I think I see why you didn't want to do this, since "The Editor" is just a framing device, and not a real editor, but I think you should still indicate which terms come from the glossary, maybe by adding a `<cite>Glossary</cite>`. Perhaps a  clarifying remark on this could be added to the long description.

**Comment by chapkachapka** [comment]
Committed all except "beast", which was resolved with reviewer. Re-reviewed italics and will respond in mailing list.
