### ISSUE TITLE
More minor points

### ISSUE THREAD

**Issue by lukasbystricky** [chapkachapka/maria-edgeworth_castle-rackrent#2]
- [x] There's a few additional words that you can look at. If you think they're Irish English then you can leave them untagged and unitalicized. 
- Ullaloo
- croteries
- cantred
- hyde (as a unit of area)
- custodiam

- [x] One modernization: postchaise -> [post chaise](https://www.merriam-webster.com/dictionary/post%20chaise)
- [x] Another thing I noticed is that you have "1800" as a footer in the preface and chapter-2. I suppose it makes sense as a date in the preface, but it's not in the PG transcription at the end of chapter 2, nor is it in the scans [here](https://archive.org/details/in.ernet.dli.2015.46995/page/n91/mode/2up) . I think it can be removed at least in chapter-2 and maybe also in the preface, although I'll leave that up to you. I think it should at least be tagged with a time tag (see SEMOS [7.7.2.3](https://standardebooks.org/manual/1.7.3/single-page#7.7.2.3))

**Comment by chapkachapka** [comment]
Modernised postchaise, removed footer dates, reviewed additional terms.
