### ISSUE TITLE
Review #3

### ISSUE THREAD

**Issue by lukasbystricky** [chapkachapka/maria-edgeworth_castle-rackrent#3]
- [x] A few more words to look at:
-  _half-cartron_: I think half should be outside the italics
- _cantred_, _cartons_, _kilt_ :unsemanticated italics, is this right?
- quaterons and hyde: not in MW, should these be tagged?

- [x] Run typogrify

**Comment by chapkachapka** [comment]
Reviewed words as requested and made some edits. Ran typogrify.
